/**
 * GENERATED by scripts/build-chain-plate.mjs — do not edit by hand.
 *
 * The reading order of a shift's marks, computed from where they land on the
 * wide plate: left to right, then top to bottom, with the enabling layers
 * last because they are the bottom row. It is deliberately NOT the order of
 * src/data/industryChain.ts, and it is shared with the narrow-screen column
 * so a number means the same thing on a phone as on a laptop.
 *
 * A target whose reading is empty at either distance carries no mark; the
 * runtime filters this list and numbers what is left from one, so the numbers
 * are always contiguous.
 */
import type { ShiftId } from '@/data/industryChain';

export const MARK_ORDER: Record<ShiftId, readonly string[]> = {
  'reindustrialisation': [
    'border-export',
    'j-extraction-processing',
    'stage-processing',
    'j-processing-trader',
    'node-trader',
    'j-trader-manufacturing',
    'border-import',
    'stage-manufacturing'
  ],
  'green': [
    'return-postconsumer-material',
    'return-postconsumer-organic',
    'stage-recovery',
    'j-consumption-recovery',
    'band-logistics',
    'band-credit',
    'band-energy'
  ]
} as const;
