/**
 * The front page, at two distances.
 *
 * Far, it reads as an economy running: an hourglass that narrows to primary
 * processing and widens after distribution. Near, every joint carries the
 * accounting instrument that measures it, set in the ledger's own register —
 * monospace, one step down. Neither reading is behind a control; the second
 * one is simply smaller, which is what "up close" means.
 *
 * Two plates, one content: the wide one lies on its side, the tall one stands
 * the hourglass upright for a narrow screen. CSS picks; both carry every node.
 * Generated by scratchpad/build.mjs — geometry is computed, not hand-placed.
 */
import './chain-plate.css';

export function ChainPlate() {
  return (
    <div className="chain-plate">
      <header>
        <h1>An economy at arm&rsquo;s length. <em>A ledger up close.</em></h1>
        <p className="props">generic across sectors &middot; the unit is the function, not the firm &middot; descriptive, not normative</p>
      </header>

      <figure>
        <svg className="plate plate--wide" viewBox="0 0 1680 830" role="img"
            aria-label="An industry chain drawn as an hourglass: many production lanes narrow to primary processing, then widen through distribution to retail and final demand.">
            <defs>
          <marker id="tip" viewBox="0 0 8 8" refX="7" refY="4" markerWidth="6" markerHeight="6" orient="auto-start-reverse">
            <path d="M 0 1 L 7 4 L 0 7 z" className="mk"/></marker>
          <marker id="tip-ret" viewBox="0 0 8 8" refX="7" refY="4" markerWidth="6" markerHeight="6" orient="auto-start-reverse">
            <path d="M 0 1 L 7 4 L 0 7 z" className="mk-acc"/></marker>
          <marker id="tip-money" viewBox="0 0 8 8" refX="7" refY="4" markerWidth="6" markerHeight="6" orient="auto-start-reverse">
            <path d="M 0 1 L 7 4 L 0 7 z" className="mk-acc"/></marker>
          <marker id="tip-info" viewBox="0 0 8 8" refX="7" refY="4" markerWidth="5" markerHeight="5" orient="auto-start-reverse">
            <path d="M 0 1 L 7 4 L 0 7 z" className="mk-soft"/></marker>
          <marker id="tip-energy" viewBox="0 0 8 8" refX="7" refY="4" markerWidth="5" markerHeight="5" orient="auto-start-reverse">
            <path d="M 0 1 L 7 4 L 0 7 z" className="mk-soft"/></marker>
        </defs><path className="hull" d="M 156,104 C 300,96 402,106 504,232 L 988,232
            C 1090,118 1240,104 1520,100 L 1520,444 C 1240,440 1090,426 988,318
            L 504,318 C 402,444 300,452 156,400 Z"/>
        <g className="strat">
              <rect x="156" y="604" width="1364" height="34"/>
              <path className="strat-top" d="M 156 604 L 1520 604"/>
              <text x="166" y="625" className="strat-t" textAnchor="start">Logistics and warehousing</text>
              <text x="560" y="625" className="strat-n" textAnchor="start">ambient · cold chain</text>
              
            </g>
        <g className="strat">
              <rect x="156" y="644" width="1364" height="34"/>
              <path className="strat-top" d="M 156 644 L 1520 644"/>
              <text x="166" y="665" className="strat-t" textAnchor="start">Credit and working capital</text>
              
              
        <g className="joint">
          <rect x="1210" y="644" width="300" height="32" fill="transparent"/>
          <text x="1510" y="657" className="macro" textAnchor="end">Monetary policy</text>
          <text x="1510" y="672" className="micro" textAnchor="end">DSO · DIO · DPO — who finances whom</text>
        </g>
            </g>
        <g className="strat">
              <rect x="156" y="684" width="1364" height="34"/>
              <path className="strat-top" d="M 156 684 L 1520 684"/>
              <text x="166" y="705" className="strat-t" textAnchor="start">Regulation, standards and fiscal status</text>
              
              
        <g className="joint">
          <rect x="1210" y="684" width="300" height="32" fill="transparent"/>
          <text x="1510" y="697" className="macro" textAnchor="end">Fiscal</text>
          <text x="1510" y="712" className="micro" textAnchor="end">output VAT less input VAT · excise payable</text>
        </g>
            </g>
        <g className="strat">
              <rect x="156" y="724" width="1364" height="34"/>
              <path className="strat-top" d="M 156 724 L 1520 724"/>
              <text x="166" y="745" className="strat-t" textAnchor="start">Contract capacity</text>
              <text x="560" y="745" className="strat-n" textAnchor="start">makloon · toll manufacturing</text>
              
            </g>
        <g className="strat">
              <rect x="156" y="764" width="1364" height="34"/>
              <path className="strat-top" d="M 156 764 L 1520 764"/>
              <text x="166" y="785" className="strat-t" textAnchor="start">Principal and distributor contractual governance</text>
              
              
            </g>
        <g className="cut"><path d="M 384 100 L 384 798"/>
            <rect x="344" y="80" width="80" height="16" className="cut-chip"/>
            <text x="384" y="92" className="cut-t" textAnchor="middle">Export</text></g>
        <g className="cut"><path d="M 490 100 L 490 798"/>
            <rect x="450" y="80" width="80" height="16" className="cut-chip"/>
            <text x="490" y="92" className="cut-t" textAnchor="middle">Import</text></g>
        <g className="cut"><path d="M 814 100 L 814 798"/>
            <rect x="774" y="80" width="80" height="16" className="cut-chip"/>
            <text x="814" y="92" className="cut-t" textAnchor="middle">Capital goods</text></g>
        <text x="150" y="112" className="lane-t" textAnchor="end">Genetics and breeding</text>
        <path className="flow-thin" d="M 156 108 C 182 108, 188 168, 206 168"/>
        <text x="150" y="142" className="lane-t" textAnchor="end">Cultivation</text>
        <path className="flow-thin" d="M 156 138 C 182 138, 188 168, 206 168"/>
        <text x="150" y="172" className="lane-t" textAnchor="end">Livestock</text>
        <path className="flow-thin" d="M 156 168 C 182 168, 188 168, 206 168"/>
        <text x="150" y="202" className="lane-t" textAnchor="end">Capture fisheries</text>
        <path className="flow-thin" d="M 156 198 C 182 198, 188 168, 206 168"/>
        <text x="150" y="360" className="lane-t" textAnchor="end">Fossil energy</text>
        <path className="flow-thin" d="M 156 356 C 182 356, 188 382, 206 382"/>
        <text x="150" y="390" className="lane-t" textAnchor="end">Minerals and ores</text>
        <path className="flow-thin" d="M 156 386 C 182 386, 188 382, 206 382"/>
        <path className="flow" d="M 374 168 C 385 168, 385 168, 396 168"/>
        <path className="flow" d="M 496 168 C 500 168, 500 275, 504 275"/>
        <path className="flow" d="M 374 382 C 439 382, 439 275, 504 275"/>
        <path className="flow" d="M 664 275 C 677 275, 677 275, 690 275"/>
        <path className="flow" d="M 800 275 C 814 275, 814 275, 828 275"/>
        <path className="flow" d="M 988 275 C 1001 275, 1001 240, 1014 240"/>
        <path className="flow" d="M 988 275 C 1001 275, 1001 316, 1014 316"/>
        <path className="flow" d="M 1124 240 C 1137 240, 1137 146, 1150 146"/>
        <path className="flow" d="M 1124 240 C 1137 240, 1137 212, 1150 212"/>
        <path className="flow" d="M 1124 316 C 1137 316, 1137 278, 1150 278"/>
        <path className="flow" d="M 1124 316 C 1137 316, 1137 344, 1150 344"/>
        <path className="flow" d="M 1124 316 C 1137 316, 1137 410, 1150 410"/>
        <path className="flow" d="M 1300 146 C 1313 146, 1313 275, 1326 275"/>
        <path className="flow" d="M 1300 212 C 1313 212, 1313 275, 1326 275"/>
        <path className="flow" d="M 1300 278 C 1313 278, 1313 275, 1326 275"/>
        <path className="flow" d="M 1300 344 C 1313 344, 1313 275, 1326 275"/>
        <path className="flow" d="M 1300 410 C 1313 410, 1313 275, 1326 275"/>
        <path className="flow" d="M 880 152 C 880 200, 886 214, 892 235" markerEnd="url(#tip)"/>
        <path className="flow-thin" d="M 892 312 L 892 394"/>
        <path className="flow" d="M 1420 420 L 1420 449" markerEnd="url(#tip)"/>
        <text x="158" y="84" className="energy-t" textAnchor="start">Energy</text>
        <path className="energy" d="M 266 110 L 266 129" markerEnd="url(#tip-energy)"/>
        <path className="energy" d="M 266 328 L 266 347" markerEnd="url(#tip-energy)"/>
        <path className="energy" d="M 560 216 L 560 235" markerEnd="url(#tip-energy)"/>
        <path className="energy" d="M 940 88 L 940 107" markerEnd="url(#tip-energy)"/>
        <path className="energy" d="M 950 216 L 950 235" markerEnd="url(#tip-energy)"/>
        <path className="energy" d="M 1470 114 L 1470 133" markerEnd="url(#tip-energy)"/>
        <path className="energy" d="M 1470 430 L 1470 449" markerEnd="url(#tip-energy)"/>
        <g className="stage stage--entry">
            <rect x="206" y="132" width="168" height="72" rx="2"/>
            <text x="216" y="166" className="stage-t stage-t--rev" textAnchor="start">Biological primary</text><text x="216" y="180" className="stage-t stage-t--rev" textAnchor="start">production</text></g>
        <g className="stage stage--entry">
            <rect x="206" y="350" width="168" height="60" rx="2"/>
            <text x="216" y="378" className="stage-t stage-t--rev" textAnchor="start">Geological</text><text x="216" y="392" className="stage-t stage-t--rev" textAnchor="start">extraction</text></g>
        <path className="entry-bar" d="M 199 132 L 199 410"/>
        
        <g className="node"><rect x="396" y="151" width="100" height="34" rx="17"/>
          <text x="408" y="172" className="node-t" textAnchor="start">Aggregation</text></g>
        <g className="stage">
            <rect x="504" y="238" width="160" height="74" rx="2"/>
            <text x="514" y="280" className="stage-t" textAnchor="start">Primary processing</text></g>
        
        <g className="node"><rect x="690" y="259" width="110" height="32" rx="16"/>
          <text x="702" y="279" className="node-t" textAnchor="start">Trader / importer</text></g>
        <g className="stage">
            <rect x="828" y="110" width="160" height="42" rx="2"/>
            <text x="838" y="136" className="stage-t" textAnchor="start">Packaging manufacture</text></g>
        <g className="stage">
            <rect x="828" y="238" width="160" height="74" rx="2"/>
            <text x="838" y="273" className="stage-t" textAnchor="start">Finished-goods</text><text x="838" y="287" className="stage-t" textAnchor="start">manufacturing</text></g>
        
        <g className="node"><rect x="828" y="394" width="160" height="32" rx="16"/>
          <text x="840" y="414" className="node-t" textAnchor="start">Brand owner / principal</text></g>
        
        <g className="node"><rect x="1014" y="225" width="110" height="30" rx="15"/>
          <text x="1026" y="244" className="node-t" textAnchor="start">Distributor</text></g>
        <text x="1028" y="268" className="recur" textAnchor="start">↳ sub-distributor · regional agent</text>
        
        <g className="node"><rect x="1014" y="301" width="110" height="30" rx="15"/>
          <text x="1026" y="320" className="node-t" textAnchor="start">Wholesaler</text></g>
        
        <g className="node"><rect x="1150" y="131" width="150" height="30" rx="15"/>
          <text x="1162" y="150" className="node-t" textAnchor="start">Warung / general trade</text></g>
        
        <g className="node"><rect x="1150" y="197" width="150" height="30" rx="15"/>
          <text x="1162" y="216" className="node-t" textAnchor="start">Modern trade</text></g>
        
        <g className="node"><rect x="1150" y="263" width="150" height="30" rx="15"/>
          <text x="1162" y="282" className="node-t" textAnchor="start">E-commerce, first party</text></g>
        
        <g className="node"><rect x="1150" y="329" width="150" height="30" rx="15"/>
          <text x="1162" y="348" className="node-t" textAnchor="start">Quick commerce</text></g>
        
        <g className="node"><rect x="1150" y="395" width="150" height="30" rx="15"/>
          <text x="1162" y="414" className="node-t" textAnchor="start">Horeca</text></g>
        <g className="stage"><rect x="1326" y="136" width="194" height="284" rx="2"/>
              <text x="1336" y="158" className="stage-t" textAnchor="start">Consumption and use</text></g>
        <g className="demand">
              <path d="M 1338 208 L 1338 224"/>
              <text x="1347" y="222" className="demand-t" textAnchor="start">Households</text></g>
        <g className="demand">
              <path d="M 1338 284 L 1338 300"/>
              <text x="1347" y="298" className="demand-t" textAnchor="start">Government and institutions</text></g>
        <g className="demand">
              <path d="M 1338 360 L 1338 376"/>
              <text x="1347" y="374" className="demand-t" textAnchor="start">Abroad</text></g>
        <g className="stage">
            <rect x="1330" y="452" width="190" height="48" rx="2"/>
            <text x="1340" y="481" className="stage-t" textAnchor="start">Recovery</text></g>
        <g className="ret">
            <path d="M 908 232 C 908 178, 584 178, 584 232" markerEnd="url(#tip-ret)"/>
            <text x="746" y="184" className="ret-t" textAnchor="middle">Scrap and reject</text></g>
        <g className="ret">
            <path d="M 1225 232 C 1225 178, 1069 178, 1069 232" markerEnd="url(#tip-ret)"/>
            <text x="1147" y="184" className="ret-t" textAnchor="middle">Commercial returns</text></g>
        <g className="ret">
            <path d="M 1225 232 C 1225 140, 908 140, 908 232" markerEnd="url(#tip-ret)"/>
            <text x="1066.5" y="146" className="ret-t" textAnchor="middle">Reusable packaging</text></g>
        <g className="ret">
              <path d="M 1520 476 L 1620 476 L 1620 38 L 278 38 L 278 128" markerEnd="url(#tip-ret)"/>
              <path d="M 560 38 L 560 234" markerEnd="url(#tip-ret)"/>
              <text x="1000" y="30" className="ret-t" textAnchor="middle">Post-consumer</text></g>
        <g className="ret">
              <path d="M 1520 206 C 1562 220, 1562 252, 1520 266" markerEnd="url(#tip-ret)"/>
              <text x="1568" y="232" className="ret-t" textAnchor="start">Secondary market</text>
              <text x="1568" y="245" className="ret-t" textAnchor="start">and refurbishment</text></g>
        <g className="byp"><path d="M 660 312 L 742 386" markerEnd="url(#tip)"/>
              <text x="750" y="396" className="byp-t" textAnchor="start">By-product → another chain</text></g>
        <g className="np">
            <path className="np-stem" d="M 374 446 L 374 552"/><path className="np-stem" d="M 490 446 L 490 552"/><path className="np-stem" d="M 664 446 L 664 552"/><path className="np-stem" d="M 800 446 L 800 552"/><path className="np-stem" d="M 1000 446 L 1000 552"/><path className="np-stem" d="M 1140 446 L 1140 552"/><path className="np-stem" d="M 1315 446 L 1315 552"/>
            <path className="np-money" d="M 1300 528 L 160 528" markerEnd="url(#tip-money)"/>
            <path className="np-info" d="M 1300 552 L 160 552" markerEnd="url(#tip-info)"/>
            <path className="np-info" d="M 160 552 L 1300 552" markerEnd="url(#tip-info)"/>
            <rect x="596" y="519" width="210.60000000000002" height="15" className="cut-chip"/><text x="600" y="530" className="np-t" textAnchor="start">Money — payment, against the goods</text>
            <rect x="596" y="543" width="364" height="15" className="cut-chip"/><text x="600" y="554" className="np-t" textAnchor="start">Information — demand signal ◁   ▷ specification and standard</text>
          </g>
        
        <g className="joint">
          <rect x="512" y="145" width="300" height="32" fill="transparent"/>
          <text x="512" y="158" className="macro" textAnchor="start">Inflation</text>
          <text x="512" y="173" className="micro" textAnchor="start">gross margin by stage · renegotiation lag</text>
        </g>
        
        <g className="joint">
          <rect x="512" y="187" width="300" height="32" fill="transparent"/>
          <text x="512" y="200" className="macro" textAnchor="start">Exchange rate</text>
          <text x="512" y="215" className="micro" textAnchor="start">foreign-exchange gain and loss</text>
        </g>
        
        <g className="joint">
          <rect x="512" y="339" width="300" height="32" fill="transparent"/>
          <text x="512" y="352" className="macro" textAnchor="start">Labour</text>
          <text x="512" y="367" className="micro" textAnchor="start">labour inside cost of goods sold</text>
        </g>
        
        <g className="joint">
          <rect x="700" y="457" width="300" height="32" fill="transparent"/>
          <text x="700" y="470" className="macro" textAnchor="start">Business cycle</text>
          <text x="700" y="485" className="micro" textAnchor="start">inventory to sales</text>
        </g>
        
        <g className="joint">
          <rect x="1020" y="457" width="300" height="32" fill="transparent"/>
          <text x="1020" y="470" className="macro" textAnchor="start">Growth</text>
          <text x="1020" y="485" className="micro" textAnchor="start">value added: revenue less purchased inputs</text>
        </g>
        
        <g className="joint">
          <rect x="156" y="567" width="300" height="32" fill="transparent"/>
          <text x="156" y="580" className="macro" textAnchor="start">External balance</text>
          <text x="156" y="595" className="micro" textAnchor="start">export revenue · import cost · landed cost</text>
        </g></svg>
        <svg className="plate plate--tall" viewBox="0 0 390 1580" role="img"
            aria-label="The same industry chain turned upright for a narrow screen: production lanes at the top narrow to primary processing, then widen through distribution to retail and final demand.">
            <defs>
          <marker id="tip" viewBox="0 0 8 8" refX="7" refY="4" markerWidth="6" markerHeight="6" orient="auto-start-reverse">
            <path d="M 0 1 L 7 4 L 0 7 z" className="mk"/></marker>
          <marker id="tip-ret" viewBox="0 0 8 8" refX="7" refY="4" markerWidth="6" markerHeight="6" orient="auto-start-reverse">
            <path d="M 0 1 L 7 4 L 0 7 z" className="mk-acc"/></marker>
          <marker id="tip-money" viewBox="0 0 8 8" refX="7" refY="4" markerWidth="6" markerHeight="6" orient="auto-start-reverse">
            <path d="M 0 1 L 7 4 L 0 7 z" className="mk-acc"/></marker>
          <marker id="tip-info" viewBox="0 0 8 8" refX="7" refY="4" markerWidth="5" markerHeight="5" orient="auto-start-reverse">
            <path d="M 0 1 L 7 4 L 0 7 z" className="mk-soft"/></marker>
          <marker id="tip-energy" viewBox="0 0 8 8" refX="7" refY="4" markerWidth="5" markerHeight="5" orient="auto-start-reverse">
            <path d="M 0 1 L 7 4 L 0 7 z" className="mk-soft"/></marker>
        </defs><path className="hull" d="M 86,150 C 82,300 138,360 132,430 L 132,790
            C 138,880 78,940 74,1120 L 306,1120 C 302,940 242,880 248,790
            L 248,430 C 242,360 298,300 294,150 Z"/>
        <g className="strat"><rect x="330" y="150" width="7" height="1080"/>
              <path className="strat-top" d="M 330 150 L 330 1230"/>
              <text x="335" y="1224" className="strat-t" textAnchor="start" transform="rotate(-90 335 1224)">Logistics and warehousing</text></g>
        <g className="strat"><rect x="342" y="150" width="7" height="1080"/>
              <path className="strat-top" d="M 342 150 L 342 1230"/>
              <text x="347" y="1224" className="strat-t" textAnchor="start" transform="rotate(-90 347 1224)">Credit and working capital</text></g>
        <g className="strat"><rect x="354" y="150" width="7" height="1080"/>
              <path className="strat-top" d="M 354 150 L 354 1230"/>
              <text x="359" y="1224" className="strat-t" textAnchor="start" transform="rotate(-90 359 1224)">Regulation, standards and fiscal status</text></g>
        <g className="strat"><rect x="366" y="150" width="7" height="1080"/>
              <path className="strat-top" d="M 366 150 L 366 1230"/>
              <text x="371" y="1224" className="strat-t" textAnchor="start" transform="rotate(-90 371 1224)">Contract capacity</text></g>
        <g className="strat"><rect x="378" y="150" width="7" height="1080"/>
              <path className="strat-top" d="M 378 150 L 378 1230"/>
              <text x="383" y="1224" className="strat-t" textAnchor="start" transform="rotate(-90 383 1224)">Principal and distributor contractual governance</text></g>
        <path className="flow-thin" d="M 96 158 C 96 196, 190 186, 190 222"/>
        <text x="100" y="152" className="lane-t" textAnchor="start" transform="rotate(-90 100 152)">Genetics and breeding</text>
        <path className="flow-thin" d="M 130 158 C 130 196, 190 186, 190 222"/>
        <text x="134" y="152" className="lane-t" textAnchor="start" transform="rotate(-90 134 152)">Cultivation</text>
        <path className="flow-thin" d="M 164 158 C 164 196, 190 186, 190 222"/>
        <text x="168" y="152" className="lane-t" textAnchor="start" transform="rotate(-90 168 152)">Livestock</text>
        <path className="flow-thin" d="M 198 158 C 198 196, 190 186, 190 222"/>
        <text x="202" y="152" className="lane-t" textAnchor="start" transform="rotate(-90 202 152)">Capture fisheries</text>
        <path className="flow-thin" d="M 232 158 C 232 196, 190 186, 190 222"/>
        <text x="236" y="152" className="lane-t" textAnchor="start" transform="rotate(-90 236 152)">Fossil energy</text>
        <path className="flow-thin" d="M 266 158 C 266 196, 190 186, 190 222"/>
        <text x="270" y="152" className="lane-t" textAnchor="start" transform="rotate(-90 270 152)">Minerals and ores</text>
        <g className="stage stage--entry">
            <rect x="86" y="220" width="208" height="44" rx="2"/>
            <text x="96" y="240" className="stage-t stage-t--rev" textAnchor="start">Biological primary</text><text x="96" y="254" className="stage-t stage-t--rev" textAnchor="start">production</text></g>
        <path className="energy" d="M 316 242 L 298 242" markerEnd="url(#tip-energy)"/>
        <g className="stage stage--entry">
            <rect x="86" y="264" width="208" height="32" rx="2"/>
            <text x="96" y="285" className="stage-t stage-t--rev" textAnchor="start">Geological extraction</text></g>
        <path className="energy" d="M 316 280 L 298 280" markerEnd="url(#tip-energy)"/>
        <path className="flow" d="M 190 296 L 190 322" markerEnd="url(#tip)"/>
        
        <g className="node"><rect x="112" y="322" width="156" height="26" rx="13"/>
          <text x="124" y="339" className="node-t" textAnchor="start">Aggregation</text></g>
        <path className="flow" d="M 190 348 L 190 380" markerEnd="url(#tip)"/>
        <g className="stage">
            <rect x="134" y="380" width="112" height="46" rx="2"/>
            <text x="144" y="401" className="stage-t" textAnchor="start">Primary</text><text x="144" y="415" className="stage-t" textAnchor="start">processing</text></g>
        <path className="energy" d="M 268 402 L 250 402" markerEnd="url(#tip-energy)"/>
        <path className="flow" d="M 190 426 L 190 452" markerEnd="url(#tip)"/>
        
        <g className="node"><rect x="124" y="452" width="132" height="26" rx="13"/>
          <text x="136" y="469" className="node-t" textAnchor="start">Trader / importer</text></g>
        <path className="flow" d="M 190 478 L 190 500" markerEnd="url(#tip)"/>
        <g className="stage">
            <rect x="128" y="500" width="124" height="44" rx="2"/>
            <text x="138" y="520" className="stage-t" textAnchor="start">Packaging</text><text x="138" y="534" className="stage-t" textAnchor="start">manufacture</text></g>
        <path className="energy" d="M 274 522 L 256 522" markerEnd="url(#tip-energy)"/>
        <path className="flow" d="M 190 544 L 190 572" markerEnd="url(#tip)"/>
        <g className="stage">
            <rect x="128" y="572" width="124" height="46" rx="2"/>
            <text x="138" y="593" className="stage-t" textAnchor="start">Finished-goods</text><text x="138" y="607" className="stage-t" textAnchor="start">manufacturing</text></g>
        <path className="energy" d="M 274 594 L 256 594" markerEnd="url(#tip-energy)"/>
        <path className="flow" d="M 190 618 L 190 648" markerEnd="url(#tip)"/>
        
        <g className="node"><rect x="110" y="648" width="160" height="26" rx="13"/>
          <text x="122" y="665" className="node-t" textAnchor="start">Brand owner / principal</text></g>
        <path className="flow" d="M 190 674 L 190 704" markerEnd="url(#tip)"/>
        
        <g className="node"><rect x="115" y="704" width="150" height="26" rx="13"/>
          <text x="127" y="721" className="node-t" textAnchor="start">Distributor</text></g>
        <text x="127" y="742" className="recur" textAnchor="start">↳ sub-distributor · regional agent</text>
        <path className="flow" d="M 190 730 L 190 750" markerEnd="url(#tip)"/>
        
        <g className="node"><rect x="115" y="750" width="150" height="26" rx="13"/>
          <text x="127" y="767" className="node-t" textAnchor="start">Wholesaler</text></g>
        <path className="flow" d="M 190 776 L 190 796" markerEnd="url(#tip)"/>
        
        <g className="node"><rect x="90" y="796" width="200" height="26" rx="13"/>
          <text x="102" y="813" className="node-t" textAnchor="start">Warung / general trade</text></g>
        
        <g className="node"><rect x="90" y="830" width="200" height="26" rx="13"/>
          <text x="102" y="847" className="node-t" textAnchor="start">Modern trade</text></g>
        
        <g className="node"><rect x="90" y="864" width="200" height="26" rx="13"/>
          <text x="102" y="881" className="node-t" textAnchor="start">E-commerce, first party</text></g>
        
        <g className="node"><rect x="90" y="898" width="200" height="26" rx="13"/>
          <text x="102" y="915" className="node-t" textAnchor="start">Quick commerce</text></g>
        
        <g className="node"><rect x="90" y="932" width="200" height="26" rx="13"/>
          <text x="102" y="949" className="node-t" textAnchor="start">Horeca</text></g>
        <path className="flow" d="M 190 966 L 190 990" markerEnd="url(#tip)"/>
        <g className="stage"><rect x="78" y="990" width="224" height="120" rx="2"/>
              <text x="88" y="1012" className="stage-t" textAnchor="start">Consumption and use</text></g>
        <path className="energy" d="M 324 1010 L 306 1010" markerEnd="url(#tip-energy)"/>
        <g className="demand">
              <path d="M 90 1033 L 90 1047"/>
              <text x="99" y="1045" className="demand-t" textAnchor="start">Households</text></g>
        <g className="demand">
              <path d="M 90 1057 L 90 1071"/>
              <text x="99" y="1069" className="demand-t" textAnchor="start">Government and institutions</text></g>
        <g className="demand">
              <path d="M 90 1081 L 90 1095"/>
              <text x="99" y="1093" className="demand-t" textAnchor="start">Abroad</text></g>
        <path className="flow" d="M 190 1110 L 190 1134" markerEnd="url(#tip)"/>
        <g className="stage">
            <rect x="105" y="1134" width="170" height="34" rx="2"/>
            <text x="115" y="1156" className="stage-t" textAnchor="start">Recovery</text></g>
        <path className="energy" d="M 297 1151 L 279 1151" markerEnd="url(#tip-energy)"/>
        <g className="byp"><path d="M 246 414 L 282 444" markerEnd="url(#tip)"/>
              <text x="250" y="462" className="byp-t" textAnchor="start">By-product →</text>
              <text x="250" y="474" className="byp-t" textAnchor="start">another chain</text></g>
        <text x="300" y="214" className="energy-t" textAnchor="start">Energy</text>
        <g className="ret">
            <path d="M 128 594 C 52 594, 52 402, 134 402" markerEnd="url(#tip-ret)"/>
            <text x="48" y="498" className="ret-t" textAnchor="middle" transform="rotate(-90 48 498)">Scrap and reject</text></g>
        <g className="ret">
            <path d="M 90 830 C 40 830, 40 717, 115 717" markerEnd="url(#tip-ret)"/>
            <text x="36" y="773.5" className="ret-t" textAnchor="middle" transform="rotate(-90 36 773.5)">Commercial returns</text></g>
        <g className="ret">
            <path d="M 90 880 C 24 880, 24 594, 128 594" markerEnd="url(#tip-ret)"/>
            <text x="20" y="737" className="ret-t" textAnchor="middle" transform="rotate(-90 20 737)">Reusable packaging</text></g>
        <g className="ret"><path d="M 105 1151 L 12 1151 L 12 241 L 86 241" markerEnd="url(#tip-ret)"/>
              <path d="M 12 402 L 134 402" markerEnd="url(#tip-ret)"/>
              <text x="8" y="700" className="ret-t" textAnchor="middle" transform="rotate(-90 8 700)">Post-consumer</text></g>
        <g className="ret"><path d="M 302 1030 C 332 1042, 332 1066, 302 1078" markerEnd="url(#tip-ret)"/>
              <text x="340" y="1054" className="ret-t" textAnchor="middle" transform="rotate(-90 340 1054)">Secondary market</text></g>
        <g className="np">
            <path className="np-stem" d="M 190 296 L 318 296"/><path className="np-stem" d="M 190 426 L 318 426"/><path className="np-stem" d="M 190 542 L 318 542"/><path className="np-stem" d="M 190 674 L 318 674"/><path className="np-stem" d="M 190 776 L 318 776"/><path className="np-stem" d="M 190 966 L 318 966"/>
            <path className="np-money" d="M 310 1120 L 310 280" markerEnd="url(#tip-money)"/>
            <path className="np-info" d="M 320 1120 L 320 280" markerEnd="url(#tip-info)"/>
            <path className="np-info" d="M 320 280 L 320 1120" markerEnd="url(#tip-info)"/>
            <text x="308" y="1230" className="np-t" textAnchor="start" transform="rotate(-90 308 1230)">Money — payment</text>
            <text x="322" y="1230" className="np-t" textAnchor="start" transform="rotate(-90 322 1230)">Information ◁ ▷</text></g>
        <path className="strat-top" d="M 8 1268 L 382 1268"/>
        <text x="8" y="1290" className="strat-t" textAnchor="start">The same joints, read close</text>
        <g className="joint"><rect x="8" y="1307" width="374" height="28" fill="transparent"/>
              <text x="8" y="1318" className="macro" textAnchor="start">Growth</text><text x="8" y="1331" className="micro" textAnchor="start">value added: revenue less purchased inputs</text></g>
        <g className="joint"><rect x="8" y="1337" width="374" height="28" fill="transparent"/>
              <text x="8" y="1348" className="macro" textAnchor="start">Inflation</text><text x="8" y="1361" className="micro" textAnchor="start">gross margin by stage · renegotiation lag</text></g>
        <g className="joint"><rect x="8" y="1367" width="374" height="28" fill="transparent"/>
              <text x="8" y="1378" className="macro" textAnchor="start">Monetary policy</text><text x="8" y="1391" className="micro" textAnchor="start">DSO · DIO · DPO — who finances whom</text></g>
        <g className="joint"><rect x="8" y="1397" width="374" height="28" fill="transparent"/>
              <text x="8" y="1408" className="macro" textAnchor="start">Exchange rate</text><text x="8" y="1421" className="micro" textAnchor="start">foreign-exchange gain and loss</text></g>
        <g className="joint"><rect x="8" y="1427" width="374" height="28" fill="transparent"/>
              <text x="8" y="1438" className="macro" textAnchor="start">External balance</text><text x="8" y="1451" className="micro" textAnchor="start">export revenue · import cost · landed cost</text></g>
        <g className="joint"><rect x="8" y="1457" width="374" height="28" fill="transparent"/>
              <text x="8" y="1468" className="macro" textAnchor="start">Fiscal</text><text x="8" y="1481" className="micro" textAnchor="start">output VAT less input VAT · excise payable</text></g>
        <g className="joint"><rect x="8" y="1487" width="374" height="28" fill="transparent"/>
              <text x="8" y="1498" className="macro" textAnchor="start">Labour</text><text x="8" y="1511" className="micro" textAnchor="start">labour inside cost of goods sold</text></g>
        <g className="joint"><rect x="8" y="1517" width="374" height="28" fill="transparent"/>
              <text x="8" y="1528" className="macro" textAnchor="start">Business cycle</text><text x="8" y="1541" className="micro" textAnchor="start">inventory to sales</text></g>
        <g className="cut"><path d="M 8 310 L 382 310"/>
            <rect x="146" y="302" width="88" height="16" className="cut-chip"/>
            <text x="190" y="314" className="cut-t" textAnchor="middle">Export</text></g>
        <g className="cut"><path d="M 8 366 L 382 366"/>
            <rect x="146" y="358" width="88" height="16" className="cut-chip"/>
            <text x="190" y="370" className="cut-t" textAnchor="middle">Import</text></g>
        <g className="cut"><path d="M 8 556 L 382 556"/>
            <rect x="146" y="548" width="88" height="16" className="cut-chip"/>
            <text x="190" y="560" className="cut-t" textAnchor="middle">Capital goods</text></g></svg>
        <figcaption>One chain. Read far, it is an economy; read near, every joint is an accounting instrument.</figcaption>
      </figure>

      <div className="sr-only">
        <ChainOutline />
      </div>
    </div>
  );
}

/** The same structure as prose, for a reader who cannot see the plate. */
function ChainOutline() {
  return (
    <>
      <h2>The chain, in reading order</h2>
      <p>Four categories, never mixed: transformation stages, intermediary nodes that take title without transforming, enabling layers that take no title at all, and physical flows that run back up the chain. The chain narrows to primary processing and widens after distribution.</p>
      <h3>Transformation stages</h3>
      <ol>
        <li>Biological primary production — Genetics and breeding, Cultivation, Livestock, Capture fisheries</li>
        <li>Geological extraction — Fossil energy, Minerals and ores</li>
        <li>Primary processing and basic industry</li>
        <li>Finished-goods manufacturing, joined by a parallel branch, Packaging manufacture</li>
        <li>Consumption and use — Households, Government and institutions, Abroad</li>
        <li>Recovery, whose output returns to processing or to primary production</li>
      </ol>
      <h3>Intermediary nodes — take title, transform nothing, record gross revenue</h3>
      <ul><li>Aggregation</li><li>Trader / importer of intermediate goods</li><li>Brand owner / principal without a factory</li>
      <li>Distributor, containing sub-distributors and regional agents</li><li>Wholesaler</li>
      <li>Stock-holding retail — Warung / general trade, Modern trade, E-commerce, first party, Quick commerce, Horeca</li></ul>
      <h3>Enabling layers — take no title, transform nothing, record net revenue</h3>
      <ul><li>Logistics and warehousing — ambient · cold chain</li><li>Credit and working capital</li><li>Regulation, standards and fiscal status</li><li>Contract capacity — makloon · toll manufacturing</li><li>Principal and distributor contractual governance</li>
      <li>Energy, drawn perpendicular into every stage rather than along the chain</li>
      <li>External sector and the border, cutting across the chain at export, import and capital goods</li></ul>
      <h3>Flows against the goods</h3>
      <ul><li>Physical returns: commercial returns, reusable packaging, scrap and reject, post-consumer, and a secondary market and refurbishment loop inside use</li>
      <li>Money, running right to left, attached at every transfer of title</li>
      <li>Information: demand signal travelling back, specification and standard travelling forward</li>
      <li>By-product, which leaves processing forward into another chain and is not a return</li></ul>
      <h3>The same joints, read off the financial statements</h3>
      <ul><li>Growth — value added: revenue less purchased inputs</li><li>Inflation — gross margin by stage and renegotiation lag</li>
      <li>Monetary policy — DSO, DIO and DPO</li><li>Exchange rate — foreign-exchange gain and loss</li>
      <li>External balance — export revenue, import cost and landed cost</li><li>Fiscal — output VAT less input VAT, and excise payable</li>
      <li>Labour — labour inside cost of goods sold</li><li>Business cycle — inventory to sales</li></ul>
    </>
  );
}
