
INSERT INTO essays (section, slug, title, module_id, finance_order, published, status, author) VALUES
-- QM1: Linear Algebra (2)
('finance','fa-01-01','Matrix Operations as Financial Infrastructure: How Covariance Matrices, Factor Loading Matrices, and OLS in Matrix Form Underlie Every Multi-Asset Risk and Regression Calculation in Finance','2c7e32b1-6cf0-479c-888a-71e1b9368f89',1,false,'draft','Dika Gustiana'),
('finance','fa-01-02','Eigenvalue Decomposition in Portfolio Analysis: How Principal Component Analysis Identifies the Dominant Sources of Portfolio Variance That Simple Correlation Analysis Misses','2c7e32b1-6cf0-479c-888a-71e1b9368f89',2,false,'draft','Dika Gustiana'),
-- QM2: Calculus (2)
('finance','fa-02-01','Optimization as Capital Decision Logic: How First-Order Conditions, Lagrange Multipliers, and the KKT Conditions Formalize the CFO''s Resource Allocation Problem','42f1fdfc-987e-4b2e-9413-d96488258461',1,false,'draft','Dika Gustiana'),
('finance','fa-02-02','Convexity in Financial Decision Problems: Why Convex Objective Functions Are Desirable, How Concavity Produces Risk Aversion, and What Both Imply for Capital Allocation Under Uncertainty','42f1fdfc-987e-4b2e-9413-d96488258461',2,false,'draft','Dika Gustiana'),
-- QM3: Probability (3)
('finance','fa-03-01','Probability Distributions in Finance: How Normal, Lognormal, and Fat-Tailed Distributions Model Different Financial Phenomena, and Why Choosing the Wrong Distribution Produces Systematically Wrong Risk Estimates','b3dd2f9c-c6e0-4cbc-adb3-0cfc4d0d929e',1,false,'draft','Dika Gustiana'),
('finance','fa-03-02','Regression Analysis for Financial Inference: OLS Assumptions, Diagnostic Testing, and How Violations of Gauss-Markov Conditions Produce Unreliable Beta, Cost of Capital, and Driver Estimates','b3dd2f9c-c6e0-4cbc-adb3-0cfc4d0d929e',2,false,'draft','Dika Gustiana'),
('finance','fa-03-03','Stochastic Processes and Option Pricing Foundations: Brownian Motion, Geometric Brownian Motion, and the Mathematical Bridge from Asset Price Dynamics to the Black-Scholes Formula','b3dd2f9c-c6e0-4cbc-adb3-0cfc4d0d929e',3,false,'draft','Dika Gustiana'),
-- 04: Ratio Architecture (3)
('finance','fa-04-01','DuPont as a Strategic Management System: How Decomposing ROE Into Profit Margin, Asset Turnover, and Financial Leverage Connects Accounting Output to Operating Strategy','5f8fe1b2-ea95-401b-b2b7-eb20be558044',1,false,'draft','Dika Gustiana'),
('finance','fa-04-02','Ratio Benchmarking Methodology: How to Select Comparable Firms, Adjust for Accounting Differences, and Interpret Cross-Sectional Ratio Dispersion Without False Precision','5f8fe1b2-ea95-401b-b2b7-eb20be558044',2,false,'draft','Dika Gustiana'),
('finance','fa-04-03','Detecting Financial Deterioration Before Default: The Sequence of Ratio Degradation — From Profitability to Coverage to Liquidity to Solvency — and the Time Lags Between Each','5f8fe1b2-ea95-401b-b2b7-eb20be558044',3,false,'draft','Dika Gustiana'),
-- 05: Unit Economics (3)
('finance','fa-05-01','Contribution Margin Architecture Across Business Models: How Unit Economics Differ Structurally Between Asset-Heavy Industrial Firms, Platform Businesses, and Subscription Models','c6218629-5e77-4117-b45c-10e7ac8f9668',1,false,'draft','Dika Gustiana'),
('finance','fa-05-02','Customer Lifetime Value and Customer Acquisition Cost: The Unit Economic Foundation for Growth Investment Decisions, and Why LTV/CAC Ratios Without Cohort-Level Data Are Almost Always Wrong','c6218629-5e77-4117-b45c-10e7ac8f9668',2,false,'draft','Dika Gustiana'),
('finance','fa-05-03','Operating Leverage Quantification: How Fixed vs. Variable Cost Structure Translates Into Earnings Volatility, and Why High Operating Leverage Changes the Optimal Capital Structure','c6218629-5e77-4117-b45c-10e7ac8f9668',3,false,'draft','Dika Gustiana'),
-- 06: Variance Decomposition (3)
('finance','fa-06-01','Price-Volume-Mix Variance Decomposition: The Mathematical Structure of Three-Way Attribution and Why the Cross-Term Assignment Convention Has Managerial Implications','5bd0c32f-ff13-4776-9b3a-be346a48e958',1,false,'draft','Dika Gustiana'),
('finance','fa-06-02','Bridge Analysis Construction for Board Reporting: How to Build a Waterfall Chart That Moves From Prior Period to Current Period Performance With Each Bridge Column Representing a Single Clean Cause','5bd0c32f-ff13-4776-9b3a-be346a48e958',2,false,'draft','Dika Gustiana'),
('finance','fa-06-03','Root Cause Isolation vs. Symptom Identification: How to Distinguish First-Order Variance Drivers From Second-Order Effects, and Why Most Variance Commentaries Stop Too Early','5bd0c32f-ff13-4776-9b3a-be346a48e958',3,false,'draft','Dika Gustiana'),
-- 07: Driver-Based Forecasting (3)
('finance','fa-07-01','Driver Tree Construction: How to Map a Business Model''s Value Creation Logic Into a Hierarchical Set of Quantifiable Drivers That Connect KPIs to Financial Line Items','682d2c62-4c0f-457f-ba6e-c3b2b4c042c9',1,false,'draft','Dika Gustiana'),
('finance','fa-07-02','Driver Sensitivity Ranking: How Partial Derivative Analysis Identifies the Two or Three Drivers That Explain 80% of Forecast Variance, and Why Everything Else Is Noise','682d2c62-4c0f-457f-ba6e-c3b2b4c042c9',2,false,'draft','Dika Gustiana'),
('finance','fa-07-03','Updating Forecasts From Driver Signals: How to Build a Forecast Update Protocol That Moves From Operational Leading Indicators to Financial Reforecast Without Waiting for Month-End Close','682d2c62-4c0f-457f-ba6e-c3b2b4c042c9',3,false,'draft','Dika Gustiana'),
-- 08: Sensitivity Analysis (3)
('finance','fa-08-01','Tornado Chart Construction and Interpretation: How One-Way Sensitivity Analysis Ranks Assumption Risk and Why the Visual Presentation of Sensitivity Changes What Decisions Get Made','feb4561a-d7e7-4ab5-8d26-85c836d91ca1',1,false,'draft','Dika Gustiana'),
('finance','fa-08-02','Monte Carlo Simulation for Capital Decisions: How to Define Probability Distributions for Key Assumptions, Run Correlated Simulations, and Interpret the Output Distribution Without Overstating Precision','feb4561a-d7e7-4ab5-8d26-85c836d91ca1',2,false,'draft','Dika Gustiana'),
('finance','fa-08-03','Decision Tree Analysis Under Sequential Uncertainty: How to Structure Staged Investment Decisions, Assign Probabilities to Branch Nodes, and Calculate Expected Value Including the Option to Stop','feb4561a-d7e7-4ab5-8d26-85c836d91ca1',3,false,'draft','Dika Gustiana'),
-- 09: Performance Dashboards (3)
('finance','fa-09-01','KPI Selection as a Governance Decision: How to Choose the Minimum Set of Metrics That Gives the Board Sufficient Information to Monitor Strategy Without Creating Reporting Theater','23b43399-59ae-459f-a082-0f5f948717fe',1,false,'draft','Dika Gustiana'),
('finance','fa-09-02','Financial Reporting for Different Audiences: How the Same Underlying Financial Data Must Be Structured Differently for the Board, the CFO''s Management Pack, the Lender Compliance Report, and the Investor Presentation','23b43399-59ae-459f-a082-0f5f948717fe',2,false,'draft','Dika Gustiana'),
('finance','fa-09-03','Leading vs. Lagging Indicators in Performance Architecture: Why Dashboards Anchored to Lagging Accounting Metrics Systematically Fail to Alert Management Early Enough to Change Outcomes','23b43399-59ae-459f-a082-0f5f948717fe',3,false,'draft','Dika Gustiana');
