-- Framework-v2 curriculum: structural completion (compact).
-- Applied via apply_migration. Enriched reference data (per-module Academic
-- Mapping tables, essay decks) is deferred to 20260731080000 (committed,
-- unapplied) to keep this migration reviewable; the 4 test modules already
-- carry academic_mapping as the proven pattern.
-- This migration: (1) t{n}-m{label} slug + display_label on all 49 modules,
-- (2) the 56 Fundamentals essay stubs the baseline never seeded,
-- (3) the Section 05 Capital Allocation row (TBD; no modules invented).
BEGIN;

-- 1. slug + display_label on all 49 modules (keyed on the UNIQUE (track,sort)).
UPDATE public.finance_modules SET slug='t1-m01', title='The Purpose of Financial Management', module_meta = coalesce(module_meta,'{}'::jsonb) || jsonb_build_object('display_label','01') WHERE track_slug='fundamentals' AND sort_order=1;
UPDATE public.finance_modules SET slug='t1-m02', title='The Business, Tax, and Financial Environment', module_meta = coalesce(module_meta,'{}'::jsonb) || jsonb_build_object('display_label','02') WHERE track_slug='fundamentals' AND sort_order=2;
UPDATE public.finance_modules SET slug='t1-m03', title='Time Value of Money', module_meta = coalesce(module_meta,'{}'::jsonb) || jsonb_build_object('display_label','03') WHERE track_slug='fundamentals' AND sort_order=3;
UPDATE public.finance_modules SET slug='t1-m04', title='Valuation of Securities and Instruments', module_meta = coalesce(module_meta,'{}'::jsonb) || jsonb_build_object('display_label','04') WHERE track_slug='fundamentals' AND sort_order=4;
UPDATE public.finance_modules SET slug='t1-m05', title='Firm Valuation: DCF and Relative Methods', module_meta = coalesce(module_meta,'{}'::jsonb) || jsonb_build_object('display_label','05') WHERE track_slug='fundamentals' AND sort_order=5;
UPDATE public.finance_modules SET slug='t1-m06', title='Risk, Return, and Portfolio Theory', module_meta = coalesce(module_meta,'{}'::jsonb) || jsonb_build_object('display_label','06') WHERE track_slug='fundamentals' AND sort_order=6;
UPDATE public.finance_modules SET slug='t1-m07', title='The CAPM, Factor Models, and the Price of Risk', module_meta = coalesce(module_meta,'{}'::jsonb) || jsonb_build_object('display_label','07') WHERE track_slug='fundamentals' AND sort_order=7;
UPDATE public.finance_modules SET slug='t1-m08a', title='Financial Statement Construction and Quality Analysis', module_meta = coalesce(module_meta,'{}'::jsonb) || jsonb_build_object('display_label','08A') WHERE track_slug='fundamentals' AND sort_order=8;
UPDATE public.finance_modules SET slug='t1-m08b', title='Financial Statement Analysis: Ratios, Profitability, and Risk Signals', module_meta = coalesce(module_meta,'{}'::jsonb) || jsonb_build_object('display_label','08B') WHERE track_slug='fundamentals' AND sort_order=9;
UPDATE public.finance_modules SET slug='t1-m09', title='Cash Flow Analysis and Financial Forecasting', module_meta = coalesce(module_meta,'{}'::jsonb) || jsonb_build_object('display_label','09') WHERE track_slug='fundamentals' AND sort_order=10;
UPDATE public.finance_modules SET slug='t1-m10', title='Working Capital Management', module_meta = coalesce(module_meta,'{}'::jsonb) || jsonb_build_object('display_label','10') WHERE track_slug='fundamentals' AND sort_order=11;
UPDATE public.finance_modules SET slug='t1-m11', title='Capital Budgeting: Principles and Decision Rules', module_meta = coalesce(module_meta,'{}'::jsonb) || jsonb_build_object('display_label','11') WHERE track_slug='fundamentals' AND sort_order=12;
UPDATE public.finance_modules SET slug='t1-m12', title='Real Options and Strategic Investment Flexibility', module_meta = coalesce(module_meta,'{}'::jsonb) || jsonb_build_object('display_label','12') WHERE track_slug='fundamentals' AND sort_order=13;
UPDATE public.finance_modules SET slug='t1-m13', title='Cost of Capital and Hurdle Rates', module_meta = coalesce(module_meta,'{}'::jsonb) || jsonb_build_object('display_label','13') WHERE track_slug='fundamentals' AND sort_order=14;
UPDATE public.finance_modules SET slug='t1-m14', title='Capital Structure: Theory and the Optimal Debt Mix', module_meta = coalesce(module_meta,'{}'::jsonb) || jsonb_build_object('display_label','14') WHERE track_slug='fundamentals' AND sort_order=15;
UPDATE public.finance_modules SET slug='t1-m14b', title='Financial Contracting and Security Design', module_meta = coalesce(module_meta,'{}'::jsonb) || jsonb_build_object('display_label','14B') WHERE track_slug='fundamentals' AND sort_order=16;
UPDATE public.finance_modules SET slug='t1-m14c', title='Debt as a Control Instrument and Governance Mechanism', module_meta = coalesce(module_meta,'{}'::jsonb) || jsonb_build_object('display_label','14C') WHERE track_slug='fundamentals' AND sort_order=17;
UPDATE public.finance_modules SET slug='t1-m15', title='Dividend Policy: Theory and Evidence', module_meta = coalesce(module_meta,'{}'::jsonb) || jsonb_build_object('display_label','15') WHERE track_slug='fundamentals' AND sort_order=18;
UPDATE public.finance_modules SET slug='t1-m16', title='Capital Markets, Instruments, and Market Efficiency', module_meta = coalesce(module_meta,'{}'::jsonb) || jsonb_build_object('display_label','16') WHERE track_slug='fundamentals' AND sort_order=19;
UPDATE public.finance_modules SET slug='t1-m17', title='International Capital Markets and Cross-Border Finance', module_meta = coalesce(module_meta,'{}'::jsonb) || jsonb_build_object('display_label','17') WHERE track_slug='fundamentals' AND sort_order=20;
UPDATE public.finance_modules SET slug='t2-m01', title='Corporate Governance and Agency Theory', module_meta = coalesce(module_meta,'{}'::jsonb) || jsonb_build_object('display_label','01') WHERE track_slug='strategic-finance' AND sort_order=1;
UPDATE public.finance_modules SET slug='t2-m02', title='Capital Allocation Strategy', module_meta = coalesce(module_meta,'{}'::jsonb) || jsonb_build_object('display_label','02') WHERE track_slug='strategic-finance' AND sort_order=2;
UPDATE public.finance_modules SET slug='t2-m03', title='M&A: Deal Architecture, Synergy Valuation, and Integration Logic', module_meta = coalesce(module_meta,'{}'::jsonb) || jsonb_build_object('display_label','03') WHERE track_slug='strategic-finance' AND sort_order=3;
UPDATE public.finance_modules SET slug='t2-m04', title='Corporate Restructuring: Logic, Triggers, and Execution', module_meta = coalesce(module_meta,'{}'::jsonb) || jsonb_build_object('display_label','04') WHERE track_slug='strategic-finance' AND sort_order=4;
UPDATE public.finance_modules SET slug='t2-m05', title='Strategic Capital Structure and Dynamic Financing Decisions', module_meta = coalesce(module_meta,'{}'::jsonb) || jsonb_build_object('display_label','05') WHERE track_slug='strategic-finance' AND sort_order=5;
UPDATE public.finance_modules SET slug='t2-m06', title='Interest Rate Risk and Debt Portfolio Management', module_meta = coalesce(module_meta,'{}'::jsonb) || jsonb_build_object('display_label','06') WHERE track_slug='strategic-finance' AND sort_order=6;
UPDATE public.finance_modules SET slug='t2-m07', title='Credit Risk, Covenant Management, and Financial Distress', module_meta = coalesce(module_meta,'{}'::jsonb) || jsonb_build_object('display_label','07') WHERE track_slug='strategic-finance' AND sort_order=7;
UPDATE public.finance_modules SET slug='t2-m08', title='Foreign Exchange Risk and Currency Management', module_meta = coalesce(module_meta,'{}'::jsonb) || jsonb_build_object('display_label','08') WHERE track_slug='strategic-finance' AND sort_order=8;
UPDATE public.finance_modules SET slug='t2-m09', title='Derivatives, Hedging Instruments, and Risk Transfer', module_meta = coalesce(module_meta,'{}'::jsonb) || jsonb_build_object('display_label','09') WHERE track_slug='strategic-finance' AND sort_order=9;
UPDATE public.finance_modules SET slug='t2-m10', title='Shareholder Signaling, Payout Design, and Activist Dynamics', module_meta = coalesce(module_meta,'{}'::jsonb) || jsonb_build_object('display_label','10') WHERE track_slug='strategic-finance' AND sort_order=10;
UPDATE public.finance_modules SET slug='t2-m11', title='Long-Term Value Architecture: ROIC, EVA, and Value Driver Systems', module_meta = coalesce(module_meta,'{}'::jsonb) || jsonb_build_object('display_label','11') WHERE track_slug='strategic-finance' AND sort_order=11;
UPDATE public.finance_modules SET slug='t2-m12', title='ESG Integration and Sustainable Capital Allocation', module_meta = coalesce(module_meta,'{}'::jsonb) || jsonb_build_object('display_label','12') WHERE track_slug='strategic-finance' AND sort_order=12;
UPDATE public.finance_modules SET slug='t2-m13', title='Political Economy, Institutional Context, and Emerging Market Finance', module_meta = coalesce(module_meta,'{}'::jsonb) || jsonb_build_object('display_label','13') WHERE track_slug='strategic-finance' AND sort_order=13;
UPDATE public.finance_modules SET slug='t3-m01', title='Budget Architecture and Integrated Financial Planning', module_meta = coalesce(module_meta,'{}'::jsonb) || jsonb_build_object('display_label','01') WHERE track_slug='planning' AND sort_order=1;
UPDATE public.finance_modules SET slug='t3-m02', title='Rolling Forecast Systems and Adaptive Planning', module_meta = coalesce(module_meta,'{}'::jsonb) || jsonb_build_object('display_label','02') WHERE track_slug='planning' AND sort_order=2;
UPDATE public.finance_modules SET slug='t3-m03', title='Scenario Planning and Stress Testing', module_meta = coalesce(module_meta,'{}'::jsonb) || jsonb_build_object('display_label','03') WHERE track_slug='planning' AND sort_order=3;
UPDATE public.finance_modules SET slug='t3-m04', title='Treasury Architecture: Cash Management, Pooling, and Short-Term Funding', module_meta = coalesce(module_meta,'{}'::jsonb) || jsonb_build_object('display_label','04') WHERE track_slug='planning' AND sort_order=4;
UPDATE public.finance_modules SET slug='t3-m05', title='Cash Runway and Liquidity Management', module_meta = coalesce(module_meta,'{}'::jsonb) || jsonb_build_object('display_label','05') WHERE track_slug='planning' AND sort_order=5;
UPDATE public.finance_modules SET slug='t3-m06', title='Working Capital Optimization and Cash Conversion', module_meta = coalesce(module_meta,'{}'::jsonb) || jsonb_build_object('display_label','06') WHERE track_slug='planning' AND sort_order=6;
UPDATE public.finance_modules SET slug='t3-m07', title='Capital Needs Planning and Funding Runway Analysis', module_meta = coalesce(module_meta,'{}'::jsonb) || jsonb_build_object('display_label','07') WHERE track_slug='planning' AND sort_order=7;
UPDATE public.finance_modules SET slug='t4-qm1', title='Quantitative Methods for Finance I: Linear Algebra and Matrix Applications', module_meta = coalesce(module_meta,'{}'::jsonb) || jsonb_build_object('display_label','QM1') WHERE track_slug='analytics' AND sort_order=1;
UPDATE public.finance_modules SET slug='t4-qm2', title='Quantitative Methods for Finance II: Calculus, Optimization, and Constrained Decision Problems', module_meta = coalesce(module_meta,'{}'::jsonb) || jsonb_build_object('display_label','QM2') WHERE track_slug='analytics' AND sort_order=2;
UPDATE public.finance_modules SET slug='t4-qm3', title='Quantitative Methods for Finance III: Probability, Statistics, and Stochastic Processes', module_meta = coalesce(module_meta,'{}'::jsonb) || jsonb_build_object('display_label','QM3') WHERE track_slug='analytics' AND sort_order=3;
UPDATE public.finance_modules SET slug='t4-m04', title='Ratio Architecture and Financial Health Diagnostics', module_meta = coalesce(module_meta,'{}'::jsonb) || jsonb_build_object('display_label','04') WHERE track_slug='analytics' AND sort_order=4;
UPDATE public.finance_modules SET slug='t4-m05', title='Unit Economics and Contribution Margin Analysis', module_meta = coalesce(module_meta,'{}'::jsonb) || jsonb_build_object('display_label','05') WHERE track_slug='analytics' AND sort_order=5;
UPDATE public.finance_modules SET slug='t4-m06', title='Variance Decomposition and Root Cause Analysis', module_meta = coalesce(module_meta,'{}'::jsonb) || jsonb_build_object('display_label','06') WHERE track_slug='analytics' AND sort_order=6;
UPDATE public.finance_modules SET slug='t4-m07', title='Driver-Based Forecasting and Business Model Mapping', module_meta = coalesce(module_meta,'{}'::jsonb) || jsonb_build_object('display_label','07') WHERE track_slug='analytics' AND sort_order=7;
UPDATE public.finance_modules SET slug='t4-m08', title='Sensitivity Analysis and Decision Modeling', module_meta = coalesce(module_meta,'{}'::jsonb) || jsonb_build_object('display_label','08') WHERE track_slug='analytics' AND sort_order=8;
UPDATE public.finance_modules SET slug='t4-m09', title='Performance Dashboards and Reporting Architecture', module_meta = coalesce(module_meta,'{}'::jsonb) || jsonb_build_object('display_label','09') WHERE track_slug='analytics' AND sort_order=9;

-- 2. Fundamentals essay stubs (56). slug ff-<mod ordinal>-<essay no>.
INSERT INTO public.essays (section, slug, title, snippet, module_id, category_id, finance_order, published, status, author)
SELECT 'finance','ff-01-01','The Objective Function of the Firm: Why Value Maximization Is Analytically Superior to Stakeholder Balance as an Organizing Principle','Why Value Maximization Is Analytically Superior to Stakeholder Balance as an Organizing Principle',(SELECT id FROM public.finance_modules WHERE track_slug='fundamentals' AND sort_order=1),(SELECT c.id FROM public.categories c JOIN public.sections s ON s.id=c.section_id WHERE s.slug='finance' AND c.slug='finance-general'),1,false,'draft'::public.content_status_enum,'Dika Gustiana'
UNION ALL
SELECT 'finance','ff-01-02','The CFO as Capital Doctrine Architect: Agency Structure, Board Mandate, and the Governance of Financial Decision Rights','Agency Structure, Board Mandate, and the Governance of Financial Decision Rights',(SELECT id FROM public.finance_modules WHERE track_slug='fundamentals' AND sort_order=1),(SELECT c.id FROM public.categories c JOIN public.sections s ON s.id=c.section_id WHERE s.slug='finance' AND c.slug='finance-general'),2,false,'draft'::public.content_status_enum,'Dika Gustiana'
UNION ALL
SELECT 'finance','ff-02-01','Tax as a Capital Structure Variable: How Legal Entity Architecture, Debt Tax Shields, and Transfer Pricing Shape After-Tax Firm Value','How Legal Entity Architecture, Debt Tax Shields, and Transfer Pricing Shape After-Tax Firm Value',(SELECT id FROM public.finance_modules WHERE track_slug='fundamentals' AND sort_order=2),(SELECT c.id FROM public.categories c JOIN public.sections s ON s.id=c.section_id WHERE s.slug='finance' AND c.slug='finance-general'),1,false,'draft'::public.content_status_enum,'Dika Gustiana'
UNION ALL
SELECT 'finance','ff-02-02','Regulatory Environment and the Cost of Capital: How Jurisdiction, Institutional Quality, and Legal Systems Price Financial Risk','How Jurisdiction, Institutional Quality, and Legal Systems Price Financial Risk',(SELECT id FROM public.finance_modules WHERE track_slug='fundamentals' AND sort_order=2),(SELECT c.id FROM public.categories c JOIN public.sections s ON s.id=c.section_id WHERE s.slug='finance' AND c.slug='finance-general'),2,false,'draft'::public.content_status_enum,'Dika Gustiana'
UNION ALL
SELECT 'finance','ff-03-01','Discounting as an Epistemological Commitment: The Mathematical and Economic Logic of Present Value in Capital Decisions','The Mathematical and Economic Logic of Present Value in Capital Decisions',(SELECT id FROM public.finance_modules WHERE track_slug='fundamentals' AND sort_order=3),(SELECT c.id FROM public.categories c JOIN public.sections s ON s.id=c.section_id WHERE s.slug='finance' AND c.slug='finance-general'),1,false,'draft'::public.content_status_enum,'Dika Gustiana'
UNION ALL
SELECT 'finance','ff-03-02','Perpetuities, Terminal Value, and the Arithmetic of Long-Duration Capital: Why Small Assumption Changes Produce Large Valuation Errors','Why Small Assumption Changes Produce Large Valuation Errors',(SELECT id FROM public.finance_modules WHERE track_slug='fundamentals' AND sort_order=3),(SELECT c.id FROM public.categories c JOIN public.sections s ON s.id=c.section_id WHERE s.slug='finance' AND c.slug='finance-general'),2,false,'draft'::public.content_status_enum,'Dika Gustiana'
UNION ALL
SELECT 'finance','ff-04-01','Bond Pricing, Duration, and Convexity: How Fixed Income Mathematics Translates Credit and Rate Risk into Price','How Fixed Income Mathematics Translates Credit and Rate Risk into Price',(SELECT id FROM public.finance_modules WHERE track_slug='fundamentals' AND sort_order=4),(SELECT c.id FROM public.categories c JOIN public.sections s ON s.id=c.section_id WHERE s.slug='finance' AND c.slug='finance-general'),1,false,'draft'::public.content_status_enum,'Dika Gustiana'
UNION ALL
SELECT 'finance','ff-04-02','Equity Valuation Models and Their Embedded Assumptions: DDM, Gordon Growth, and the Conditions Under Which They Fail','DDM, Gordon Growth, and the Conditions Under Which They Fail',(SELECT id FROM public.finance_modules WHERE track_slug='fundamentals' AND sort_order=4),(SELECT c.id FROM public.categories c JOIN public.sections s ON s.id=c.section_id WHERE s.slug='finance' AND c.slug='finance-general'),2,false,'draft'::public.content_status_enum,'Dika Gustiana'
UNION ALL
SELECT 'finance','ff-04-03','Instrument Design and Pricing Implications: Why the Form of a Security Affects Its Cost and Risk Profile Before Any Trade Is Made','Why the Form of a Security Affects Its Cost and Risk Profile Before Any Trade Is Made',(SELECT id FROM public.finance_modules WHERE track_slug='fundamentals' AND sort_order=4),(SELECT c.id FROM public.categories c JOIN public.sections s ON s.id=c.section_id WHERE s.slug='finance' AND c.slug='finance-general'),3,false,'draft'::public.content_status_enum,'Dika Gustiana'
UNION ALL
SELECT 'finance','ff-05-01','FCFF vs. FCFE: When to Value the Firm and When to Value Equity, and Why the Choice Is Never Arbitrary','When to Value the Firm and When to Value Equity, and Why the Choice Is Never Arbitrary',(SELECT id FROM public.finance_modules WHERE track_slug='fundamentals' AND sort_order=5),(SELECT c.id FROM public.categories c JOIN public.sections s ON s.id=c.section_id WHERE s.slug='finance' AND c.slug='finance-general'),1,false,'draft'::public.content_status_enum,'Dika Gustiana'
UNION ALL
SELECT 'finance','ff-05-02','Terminal Value Architecture: Why 60–80% of DCF Value Lives in a Number That Depends Entirely on Assumptions About the Distant Future','Why 60–80% of DCF Value Lives in a Number That Depends Entirely on Assumptions About the Distant Future',(SELECT id FROM public.finance_modules WHERE track_slug='fundamentals' AND sort_order=5),(SELECT c.id FROM public.categories c JOIN public.sections s ON s.id=c.section_id WHERE s.slug='finance' AND c.slug='finance-general'),2,false,'draft'::public.content_status_enum,'Dika Gustiana'
UNION ALL
SELECT 'finance','ff-05-03','Multiples as Compressed DCF Models: The Theoretical Basis for EV/EBITDA, P/E, and P/B and Their Systematic Failure Modes','The Theoretical Basis for EV/EBITDA, P/E, and P/B and Their Systematic Failure Modes',(SELECT id FROM public.finance_modules WHERE track_slug='fundamentals' AND sort_order=5),(SELECT c.id FROM public.categories c JOIN public.sections s ON s.id=c.section_id WHERE s.slug='finance' AND c.slug='finance-general'),3,false,'draft'::public.content_status_enum,'Dika Gustiana'
UNION ALL
SELECT 'finance','ff-05-04','Sum-of-Parts Valuation in Conglomerate and Holding Company Structures: When Segment Disaggregation Reveals the Conglomerate Discount','When Segment Disaggregation Reveals the Conglomerate Discount',(SELECT id FROM public.finance_modules WHERE track_slug='fundamentals' AND sort_order=5),(SELECT c.id FROM public.categories c JOIN public.sections s ON s.id=c.section_id WHERE s.slug='finance' AND c.slug='finance-general'),4,false,'draft'::public.content_status_enum,'Dika Gustiana'
UNION ALL
SELECT 'finance','ff-06-01','Diversification as a Free Lunch: The Mathematics of Covariance Reduction and the Efficient Frontier','The Mathematics of Covariance Reduction and the Efficient Frontier',(SELECT id FROM public.finance_modules WHERE track_slug='fundamentals' AND sort_order=6),(SELECT c.id FROM public.categories c JOIN public.sections s ON s.id=c.section_id WHERE s.slug='finance' AND c.slug='finance-general'),1,false,'draft'::public.content_status_enum,'Dika Gustiana'
UNION ALL
SELECT 'finance','ff-06-02','Systematic Risk vs. Idiosyncratic Risk: Why Only One Type Is Priced in Equilibrium and What That Means for Capital Allocation','Why Only One Type Is Priced in Equilibrium and What That Means for Capital Allocation',(SELECT id FROM public.finance_modules WHERE track_slug='fundamentals' AND sort_order=6),(SELECT c.id FROM public.categories c JOIN public.sections s ON s.id=c.section_id WHERE s.slug='finance' AND c.slug='finance-general'),2,false,'draft'::public.content_status_enum,'Dika Gustiana'
UNION ALL
SELECT 'finance','ff-06-03','Portfolio Theory Under Non-Normal Distributions: Skewness, Fat Tails, and the Failure of Variance as a Complete Risk Measure','Skewness, Fat Tails, and the Failure of Variance as a Complete Risk Measure',(SELECT id FROM public.finance_modules WHERE track_slug='fundamentals' AND sort_order=6),(SELECT c.id FROM public.categories c JOIN public.sections s ON s.id=c.section_id WHERE s.slug='finance' AND c.slug='finance-general'),3,false,'draft'::public.content_status_enum,'Dika Gustiana'
UNION ALL
SELECT 'finance','ff-07-01','The Capital Asset Pricing Model: Derivation, Empirical Failures, and Why It Remains the Default Discount Rate Framework','Derivation, Empirical Failures, and Why It Remains the Default Discount Rate Framework',(SELECT id FROM public.finance_modules WHERE track_slug='fundamentals' AND sort_order=7),(SELECT c.id FROM public.categories c JOIN public.sections s ON s.id=c.section_id WHERE s.slug='finance' AND c.slug='finance-general'),1,false,'draft'::public.content_status_enum,'Dika Gustiana'
UNION ALL
SELECT 'finance','ff-07-02','Fama-French Three-Factor and Five-Factor Models: What Value, Size, Profitability, and Investment Premia Say About Market Pricing','What Value, Size, Profitability, and Investment Premia Say About Market Pricing',(SELECT id FROM public.finance_modules WHERE track_slug='fundamentals' AND sort_order=7),(SELECT c.id FROM public.categories c JOIN public.sections s ON s.id=c.section_id WHERE s.slug='finance' AND c.slug='finance-general'),2,false,'draft'::public.content_status_enum,'Dika Gustiana'
UNION ALL
SELECT 'finance','ff-07-03','Beta Estimation in Practice: Mean Reversion, Leverage Adjustment, Industry Proxies, and the Measurement Problem That Undermines Every WACC','Mean Reversion, Leverage Adjustment, Industry Proxies, and the Measurement Problem That Undermines Every WACC',(SELECT id FROM public.finance_modules WHERE track_slug='fundamentals' AND sort_order=7),(SELECT c.id FROM public.categories c JOIN public.sections s ON s.id=c.section_id WHERE s.slug='finance' AND c.slug='finance-general'),3,false,'draft'::public.content_status_enum,'Dika Gustiana'
UNION ALL
SELECT 'finance','ff-08-01','Revenue Recognition and Accruals Engineering: How Accounting Choices Distort Reported Income Without Affecting Cash','How Accounting Choices Distort Reported Income Without Affecting Cash',(SELECT id FROM public.finance_modules WHERE track_slug='fundamentals' AND sort_order=8),(SELECT c.id FROM public.categories c JOIN public.sections s ON s.id=c.section_id WHERE s.slug='finance' AND c.slug='finance-general'),1,false,'draft'::public.content_status_enum,'Dika Gustiana'
UNION ALL
SELECT 'finance','ff-08-02','Off-Balance-Sheet Financing and Liability Concealment: Operating Leases, SPVs, and Contingent Obligations as Hidden Capital Structure','Operating Leases, SPVs, and Contingent Obligations as Hidden Capital Structure',(SELECT id FROM public.finance_modules WHERE track_slug='fundamentals' AND sort_order=8),(SELECT c.id FROM public.categories c JOIN public.sections s ON s.id=c.section_id WHERE s.slug='finance' AND c.slug='finance-general'),2,false,'draft'::public.content_status_enum,'Dika Gustiana'
UNION ALL
SELECT 'finance','ff-08-03','Cash Flow Statement as the Truth Document: Why Free Cash Flow Cannot Be Manipulated in the Same Way Earnings Can','Why Free Cash Flow Cannot Be Manipulated in the Same Way Earnings Can',(SELECT id FROM public.finance_modules WHERE track_slug='fundamentals' AND sort_order=8),(SELECT c.id FROM public.categories c JOIN public.sections s ON s.id=c.section_id WHERE s.slug='finance' AND c.slug='finance-general'),3,false,'draft'::public.content_status_enum,'Dika Gustiana'
UNION ALL
SELECT 'finance','ff-09-01','DuPont Decomposition as a Strategic Diagnostic: How ROE Can Rise While the Business Deteriorates','How ROE Can Rise While the Business Deteriorates',(SELECT id FROM public.finance_modules WHERE track_slug='fundamentals' AND sort_order=9),(SELECT c.id FROM public.categories c JOIN public.sections s ON s.id=c.section_id WHERE s.slug='finance' AND c.slug='finance-general'),1,false,'draft'::public.content_status_enum,'Dika Gustiana'
UNION ALL
SELECT 'finance','ff-09-02','Profitability Analysis Across the Income Statement: Why Gross Margin, EBIT Margin, and NOPAT Tell Different Stories About Competitive Position','Why Gross Margin, EBIT Margin, and NOPAT Tell Different Stories About Competitive Position',(SELECT id FROM public.finance_modules WHERE track_slug='fundamentals' AND sort_order=9),(SELECT c.id FROM public.categories c JOIN public.sections s ON s.id=c.section_id WHERE s.slug='finance' AND c.slug='finance-general'),2,false,'draft'::public.content_status_enum,'Dika Gustiana'
UNION ALL
SELECT 'finance','ff-09-03','Distress Prediction from Financial Statements: Altman Z-Score, Ohlson O-Score, and the Limits of Formula-Based Early Warning Systems','Altman Z-Score, Ohlson O-Score, and the Limits of Formula-Based Early Warning Systems',(SELECT id FROM public.finance_modules WHERE track_slug='fundamentals' AND sort_order=9),(SELECT c.id FROM public.categories c JOIN public.sections s ON s.id=c.section_id WHERE s.slug='finance' AND c.slug='finance-general'),3,false,'draft'::public.content_status_enum,'Dika Gustiana'
UNION ALL
SELECT 'finance','ff-10-01','The Three-Statement Model as an Epistemological Framework: How IS, BS, and CF Constraints Discipline Financial Assumptions','How IS, BS, and CF Constraints Discipline Financial Assumptions',(SELECT id FROM public.finance_modules WHERE track_slug='fundamentals' AND sort_order=10),(SELECT c.id FROM public.categories c JOIN public.sections s ON s.id=c.section_id WHERE s.slug='finance' AND c.slug='finance-general'),1,false,'draft'::public.content_status_enum,'Dika Gustiana'
UNION ALL
SELECT 'finance','ff-10-02','Free Cash Flow Derivation: The Accounting-to-Economics Translation That Most Financial Models Get Wrong','The Accounting-to-Economics Translation That Most Financial Models Get Wrong',(SELECT id FROM public.finance_modules WHERE track_slug='fundamentals' AND sort_order=10),(SELECT c.id FROM public.categories c JOIN public.sections s ON s.id=c.section_id WHERE s.slug='finance' AND c.slug='finance-general'),2,false,'draft'::public.content_status_enum,'Dika Gustiana'
UNION ALL
SELECT 'finance','ff-10-03','Integrated Forecasting Under Uncertainty: Assumptions Architecture, Circularity Management, and Model Hygiene in Complex Financial Projections','Assumptions Architecture, Circularity Management, and Model Hygiene in Complex Financial Projections',(SELECT id FROM public.finance_modules WHERE track_slug='fundamentals' AND sort_order=10),(SELECT c.id FROM public.categories c JOIN public.sections s ON s.id=c.section_id WHERE s.slug='finance' AND c.slug='finance-general'),3,false,'draft'::public.content_status_enum,'Dika Gustiana'
UNION ALL
SELECT 'finance','ff-11-01','The Cash Conversion Cycle as a Capital Decision: Why Working Capital Is Operating Capital and Must Be Funded as Such','Why Working Capital Is Operating Capital and Must Be Funded as Such',(SELECT id FROM public.finance_modules WHERE track_slug='fundamentals' AND sort_order=11),(SELECT c.id FROM public.categories c JOIN public.sections s ON s.id=c.section_id WHERE s.slug='finance' AND c.slug='finance-general'),1,false,'draft'::public.content_status_enum,'Dika Gustiana'
UNION ALL
SELECT 'finance','ff-11-02','Receivables, Payables, and Inventory Trade-offs: How Working Capital Optimization Creates and Destroys Value Simultaneously Across the Supply Chain','How Working Capital Optimization Creates and Destroys Value Simultaneously Across the Supply Chain',(SELECT id FROM public.finance_modules WHERE track_slug='fundamentals' AND sort_order=11),(SELECT c.id FROM public.categories c JOIN public.sections s ON s.id=c.section_id WHERE s.slug='finance' AND c.slug='finance-general'),2,false,'draft'::public.content_status_enum,'Dika Gustiana'
UNION ALL
SELECT 'finance','ff-12-01','NPV as the Foundational Capital Allocation Criterion: Why IRR, Payback, and MIRR Are Approximations of an Idea NPV Expresses Exactly','Why IRR, Payback, and MIRR Are Approximations of an Idea NPV Expresses Exactly',(SELECT id FROM public.finance_modules WHERE track_slug='fundamentals' AND sort_order=12),(SELECT c.id FROM public.categories c JOIN public.sections s ON s.id=c.section_id WHERE s.slug='finance' AND c.slug='finance-general'),1,false,'draft'::public.content_status_enum,'Dika Gustiana'
UNION ALL
SELECT 'finance','ff-12-02','Incremental Cash Flow Analysis: Side Costs, Cannibalization, Opportunity Costs, and the Systematic Errors That Inflate Project Returns','Side Costs, Cannibalization, Opportunity Costs, and the Systematic Errors That Inflate Project Returns',(SELECT id FROM public.finance_modules WHERE track_slug='fundamentals' AND sort_order=12),(SELECT c.id FROM public.categories c JOIN public.sections s ON s.id=c.section_id WHERE s.slug='finance' AND c.slug='finance-general'),2,false,'draft'::public.content_status_enum,'Dika Gustiana'
UNION ALL
SELECT 'finance','ff-12-03','Capital Rationing and Mutually Exclusive Projects: How Portfolio Constraints Change the Optimal Investment Decision','How Portfolio Constraints Change the Optimal Investment Decision',(SELECT id FROM public.finance_modules WHERE track_slug='fundamentals' AND sort_order=12),(SELECT c.id FROM public.categories c JOIN public.sections s ON s.id=c.section_id WHERE s.slug='finance' AND c.slug='finance-general'),3,false,'draft'::public.content_status_enum,'Dika Gustiana'
UNION ALL
SELECT 'finance','ff-13-01','Real Options as Anti-NPV Correction: When Deferral, Expansion, and Abandonment Rights Are Worth More Than the Base Case Cash Flows','When Deferral, Expansion, and Abandonment Rights Are Worth More Than the Base Case Cash Flows',(SELECT id FROM public.finance_modules WHERE track_slug='fundamentals' AND sort_order=13),(SELECT c.id FROM public.categories c JOIN public.sections s ON s.id=c.section_id WHERE s.slug='finance' AND c.slug='finance-general'),1,false,'draft'::public.content_status_enum,'Dika Gustiana'
UNION ALL
SELECT 'finance','ff-13-02','Decision Tree Analysis and Option Pricing in Capital Budgeting: From Qualitative Intuition to Quantifiable Strategic Premiums','From Qualitative Intuition to Quantifiable Strategic Premiums',(SELECT id FROM public.finance_modules WHERE track_slug='fundamentals' AND sort_order=13),(SELECT c.id FROM public.categories c JOIN public.sections s ON s.id=c.section_id WHERE s.slug='finance' AND c.slug='finance-general'),2,false,'draft'::public.content_status_enum,'Dika Gustiana'
UNION ALL
SELECT 'finance','ff-13-03','The Option to Abandon as a Risk Management Tool: How Exit Rights Change the Ex-Ante Investment Decision for Capital-Intensive Projects','How Exit Rights Change the Ex-Ante Investment Decision for Capital-Intensive Projects',(SELECT id FROM public.finance_modules WHERE track_slug='fundamentals' AND sort_order=13),(SELECT c.id FROM public.categories c JOIN public.sections s ON s.id=c.section_id WHERE s.slug='finance' AND c.slug='finance-general'),3,false,'draft'::public.content_status_enum,'Dika Gustiana'
UNION ALL
SELECT 'finance','ff-14-01','WACC Construction and Its Five Most Common Errors: Market Weights, Marginal Cost, Tax Shield Timing, Beta Adjustment, and the Circularity Problem','Market Weights, Marginal Cost, Tax Shield Timing, Beta Adjustment, and the Circularity Problem',(SELECT id FROM public.finance_modules WHERE track_slug='fundamentals' AND sort_order=14),(SELECT c.id FROM public.categories c JOIN public.sections s ON s.id=c.section_id WHERE s.slug='finance' AND c.slug='finance-general'),1,false,'draft'::public.content_status_enum,'Dika Gustiana'
UNION ALL
SELECT 'finance','ff-14-02','Divisional Hurdle Rates and the Capital Allocation Distortion Created by Firm-Wide WACC: How Uniform Discount Rates Systematically Misallocate Investment','How Uniform Discount Rates Systematically Misallocate Investment',(SELECT id FROM public.finance_modules WHERE track_slug='fundamentals' AND sort_order=14),(SELECT c.id FROM public.categories c JOIN public.sections s ON s.id=c.section_id WHERE s.slug='finance' AND c.slug='finance-general'),2,false,'draft'::public.content_status_enum,'Dika Gustiana'
UNION ALL
SELECT 'finance','ff-14-03','Country Risk Premium Estimation for Emerging Markets: Damodaran Methodology, CDS Spreads, and the Debate Over Whether Political Risk Is Diversifiable','Damodaran Methodology, CDS Spreads, and the Debate Over Whether Political Risk Is Diversifiable',(SELECT id FROM public.finance_modules WHERE track_slug='fundamentals' AND sort_order=14),(SELECT c.id FROM public.categories c JOIN public.sections s ON s.id=c.section_id WHERE s.slug='finance' AND c.slug='finance-general'),3,false,'draft'::public.content_status_enum,'Dika Gustiana'
UNION ALL
SELECT 'finance','ff-15-01','Modigliani-Miller Propositions I and II: The Logic of Irrelevance, Why It Holds in Theory, and the Specific Frictions That Destroy It in Practice','The Logic of Irrelevance, Why It Holds in Theory, and the Specific Frictions That Destroy It in Practice',(SELECT id FROM public.finance_modules WHERE track_slug='fundamentals' AND sort_order=15),(SELECT c.id FROM public.categories c JOIN public.sections s ON s.id=c.section_id WHERE s.slug='finance' AND c.slug='finance-general'),1,false,'draft'::public.content_status_enum,'Dika Gustiana'
UNION ALL
SELECT 'finance','ff-15-02','Trade-Off Theory vs. Pecking Order: Two Internally Consistent Frameworks That Predict Opposite Financing Behavior in Growing Firms','Two Internally Consistent Frameworks That Predict Opposite Financing Behavior in Growing Firms',(SELECT id FROM public.finance_modules WHERE track_slug='fundamentals' AND sort_order=15),(SELECT c.id FROM public.categories c JOIN public.sections s ON s.id=c.section_id WHERE s.slug='finance' AND c.slug='finance-general'),2,false,'draft'::public.content_status_enum,'Dika Gustiana'
UNION ALL
SELECT 'finance','ff-15-03','Optimal Leverage and the Operating Income Approach: How to Find the Debt Level That Minimizes WACC Without Relying on MM''s Perfect Market Assumptions','How to Find the Debt Level That Minimizes WACC Without Relying on MM''s Perfect Market Assumptions',(SELECT id FROM public.finance_modules WHERE track_slug='fundamentals' AND sort_order=15),(SELECT c.id FROM public.categories c JOIN public.sections s ON s.id=c.section_id WHERE s.slug='finance' AND c.slug='finance-general'),3,false,'draft'::public.content_status_enum,'Dika Gustiana'
UNION ALL
SELECT 'finance','ff-16-01','Adverse Selection and the Lemons Problem in Corporate Financing: Why Information Asymmetry Between Managers and Investors Determines Security Choice','Why Information Asymmetry Between Managers and Investors Determines Security Choice',(SELECT id FROM public.finance_modules WHERE track_slug='fundamentals' AND sort_order=16),(SELECT c.id FROM public.categories c JOIN public.sections s ON s.id=c.section_id WHERE s.slug='finance' AND c.slug='finance-general'),1,false,'draft'::public.content_status_enum,'Dika Gustiana'
UNION ALL
SELECT 'finance','ff-16-02','Moral Hazard and Incentive-Compatible Financing: How Convertibles, Warrants, and Covenants Solve the Asset Substitution Problem','How Convertibles, Warrants, and Covenants Solve the Asset Substitution Problem',(SELECT id FROM public.finance_modules WHERE track_slug='fundamentals' AND sort_order=16),(SELECT c.id FROM public.categories c JOIN public.sections s ON s.id=c.section_id WHERE s.slug='finance' AND c.slug='finance-general'),2,false,'draft'::public.content_status_enum,'Dika Gustiana'
UNION ALL
SELECT 'finance','ff-16-03','Security Design from First Principles: Why Debt, Equity, and Hybrids Exist as Distinct Instruments Rather Than Points on a Single Continuum','Why Debt, Equity, and Hybrids Exist as Distinct Instruments Rather Than Points on a Single Continuum',(SELECT id FROM public.finance_modules WHERE track_slug='fundamentals' AND sort_order=16),(SELECT c.id FROM public.categories c JOIN public.sections s ON s.id=c.section_id WHERE s.slug='finance' AND c.slug='finance-general'),3,false,'draft'::public.content_status_enum,'Dika Gustiana'
UNION ALL
SELECT 'finance','ff-17-01','Debt as a Disciplining Device: How Leverage Constrains Managerial Free Cash Flow and Forces Investment Discipline Without Board Intervention','How Leverage Constrains Managerial Free Cash Flow and Forces Investment Discipline Without Board Intervention',(SELECT id FROM public.finance_modules WHERE track_slug='fundamentals' AND sort_order=17),(SELECT c.id FROM public.categories c JOIN public.sections s ON s.id=c.section_id WHERE s.slug='finance' AND c.slug='finance-general'),1,false,'draft'::public.content_status_enum,'Dika Gustiana'
UNION ALL
SELECT 'finance','ff-17-02','Control Rights in Debt Contracts: How Covenant Architecture Allocates Decision Authority Between Managers and Creditors as Firm Performance Varies','How Covenant Architecture Allocates Decision Authority Between Managers and Creditors as Firm Performance Varies',(SELECT id FROM public.finance_modules WHERE track_slug='fundamentals' AND sort_order=17),(SELECT c.id FROM public.categories c JOIN public.sections s ON s.id=c.section_id WHERE s.slug='finance' AND c.slug='finance-general'),2,false,'draft'::public.content_status_enum,'Dika Gustiana'
UNION ALL
SELECT 'finance','ff-17-03','The Market for Corporate Control: Hostile Takeovers, the Free-Rider Problem, and Why Grossman-Hart Changes the Economics of Minority Shareholding','Hostile Takeovers, the Free-Rider Problem, and Why Grossman-Hart Changes the Economics of Minority Shareholding',(SELECT id FROM public.finance_modules WHERE track_slug='fundamentals' AND sort_order=17),(SELECT c.id FROM public.categories c JOIN public.sections s ON s.id=c.section_id WHERE s.slug='finance' AND c.slug='finance-general'),3,false,'draft'::public.content_status_enum,'Dika Gustiana'
UNION ALL
SELECT 'finance','ff-18-01','Dividend Irrelevance and Its Conditions: Why Modigliani-Miller''s Proof Is Correct Inside a Model That No Real Firm Inhabits','Why Modigliani-Miller''s Proof Is Correct Inside a Model That No Real Firm Inhabits',(SELECT id FROM public.finance_modules WHERE track_slug='fundamentals' AND sort_order=18),(SELECT c.id FROM public.categories c JOIN public.sections s ON s.id=c.section_id WHERE s.slug='finance' AND c.slug='finance-general'),1,false,'draft'::public.content_status_enum,'Dika Gustiana'
UNION ALL
SELECT 'finance','ff-18-02','Signaling, Clientele Effects, and the Tax Argument: The Three Competing Explanations for Why Dividend Policy Changes Move Stock Prices','The Three Competing Explanations for Why Dividend Policy Changes Move Stock Prices',(SELECT id FROM public.finance_modules WHERE track_slug='fundamentals' AND sort_order=18),(SELECT c.id FROM public.categories c JOIN public.sections s ON s.id=c.section_id WHERE s.slug='finance' AND c.slug='finance-general'),2,false,'draft'::public.content_status_enum,'Dika Gustiana'
UNION ALL
SELECT 'finance','ff-19-01','The Efficient Market Hypothesis Across Its Three Forms: What Each Form Implies for Security Analysis, Active Management, and Corporate Financing Decisions','What Each Form Implies for Security Analysis, Active Management, and Corporate Financing Decisions',(SELECT id FROM public.finance_modules WHERE track_slug='fundamentals' AND sort_order=19),(SELECT c.id FROM public.categories c JOIN public.sections s ON s.id=c.section_id WHERE s.slug='finance' AND c.slug='finance-general'),1,false,'draft'::public.content_status_enum,'Dika Gustiana'
UNION ALL
SELECT 'finance','ff-19-02','Behavioral Finance and Market Anomalies: Momentum, Value Premium, Post-Earnings Drift, and What Persistent Anomalies Tell Us About How Prices Are Set','Momentum, Value Premium, Post-Earnings Drift, and What Persistent Anomalies Tell Us About How Prices Are Set',(SELECT id FROM public.finance_modules WHERE track_slug='fundamentals' AND sort_order=19),(SELECT c.id FROM public.categories c JOIN public.sections s ON s.id=c.section_id WHERE s.slug='finance' AND c.slug='finance-general'),2,false,'draft'::public.content_status_enum,'Dika Gustiana'
UNION ALL
SELECT 'finance','ff-19-03','Capital Markets Structure and the Economics of Issuance: Why the Method of Raising Capital Affects Its Cost and Signal','Why the Method of Raising Capital Affects Its Cost and Signal',(SELECT id FROM public.finance_modules WHERE track_slug='fundamentals' AND sort_order=19),(SELECT c.id FROM public.categories c JOIN public.sections s ON s.id=c.section_id WHERE s.slug='finance' AND c.slug='finance-general'),3,false,'draft'::public.content_status_enum,'Dika Gustiana'
UNION ALL
SELECT 'finance','ff-20-01','Cross-Border Capital Structure: How Tax Treaties, Capital Controls, Thin Capitalization Rules, and Jurisdictional Arbitrage Determine Optimal Financing for Multinationals','How Tax Treaties, Capital Controls, Thin Capitalization Rules, and Jurisdictional Arbitrage Determine Optimal Financing for Multinationals',(SELECT id FROM public.finance_modules WHERE track_slug='fundamentals' AND sort_order=20),(SELECT c.id FROM public.categories c JOIN public.sections s ON s.id=c.section_id WHERE s.slug='finance' AND c.slug='finance-general'),1,false,'draft'::public.content_status_enum,'Dika Gustiana'
UNION ALL
SELECT 'finance','ff-20-02','Country Risk and the Cost of Capital in Emerging Markets: Sovereign Spreads, Political Risk Insurance, and the Limits of Quantitative Country Risk Models','Sovereign Spreads, Political Risk Insurance, and the Limits of Quantitative Country Risk Models',(SELECT id FROM public.finance_modules WHERE track_slug='fundamentals' AND sort_order=20),(SELECT c.id FROM public.categories c JOIN public.sections s ON s.id=c.section_id WHERE s.slug='finance' AND c.slug='finance-general'),2,false,'draft'::public.content_status_enum,'Dika Gustiana'
UNION ALL
SELECT 'finance','ff-20-03','ASEAN Capital Markets Architecture: Depth, Liquidity, Instrument Availability, and the Constraints They Place on Capital Allocation for Indonesian Multinationals','Depth, Liquidity, Instrument Availability, and the Constraints They Place on Capital Allocation for Indonesian Multinationals',(SELECT id FROM public.finance_modules WHERE track_slug='fundamentals' AND sort_order=20),(SELECT c.id FROM public.categories c JOIN public.sections s ON s.id=c.section_id WHERE s.slug='finance' AND c.slug='finance-general'),3,false,'draft'::public.content_status_enum,'Dika Gustiana'
ON CONFLICT (slug) DO NOTHING;

-- 3. Section 05 Capital Allocation (framework: modules+essays TBD).
INSERT INTO public.finance_sections (slug, title, description, icon, sort_order)
VALUES ('capital-allocation','Capital Allocation',
        'Capital doctrine and portfolio logic. Modules to be defined (framework marks this section TBD).','Layers',5)
ON CONFLICT (slug) DO NOTHING;

DO $a$
DECLARE n int;
BEGIN
  SELECT count(*) INTO n FROM public.finance_modules WHERE slug ~ '^t[0-9]-';
  IF n <> 49 THEN RAISE EXCEPTION 'expected 49 t-slug modules, found %', n; END IF;
  SELECT count(*) INTO n FROM public.essays WHERE slug ~ '^(ff|sf|pf|fa)-[0-9]{2}-[0-9]{2}$';
  IF n <> 161 THEN RAISE EXCEPTION 'expected 161 curriculum stubs, found %', n; END IF;
  SELECT count(*) INTO n FROM public.essays WHERE slug ~ '^ff-' AND module_id IS NULL;
  IF n > 0 THEN RAISE EXCEPTION '% fundamentals stubs have NULL module_id', n; END IF;
  SELECT count(*) INTO n FROM public.finance_sections;
  IF n <> 5 THEN RAISE EXCEPTION 'expected 5 finance_sections, found %', n; END IF;
END $a$;
COMMIT;